"""empty message

Revision ID: 0e8a71b65c3b
Revises: 
Create Date: 2024-10-11 12:38:22.671802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a71b65c3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('golds', sa.Integer(), nullable=True),
    sa.Column('silvers', sa.Integer(), nullable=True),
    sa.Column('bronzes', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('golds', sa.Integer(), nullable=True),
    sa.Column('silvers', sa.Integer(), nullable=True),
    sa.Column('bronzes', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('first_place', sa.Integer(), nullable=True),
    sa.Column('second_place', sa.Integer(), nullable=True),
    sa.Column('third_place', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_place'], ['user.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['second_place'], ['user.id'], ),
    sa.ForeignKeyConstraint(['third_place'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants_forums',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('requesters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requesters')
    op.drop_table('participants_forums')
    op.drop_table('event')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('forum')
    op.drop_table('club')
    # ### end Alembic commands ###
