"""empty message

Revision ID: 104760a79dc7
Revises: a713049dcaf9
Create Date: 2024-10-11 14:49:13.653583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104760a79dc7'
down_revision = 'a713049dcaf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managers')
    # ### end Alembic commands ###
