"""empty message

Revision ID: 5a260a820697
Revises: d1103fadeb4d
Create Date: 2024-10-14 20:50:59.425047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a260a820697'
down_revision = 'd1103fadeb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sub_event_positions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_event_id'], ['sub_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sub_event_id')
    )
    with op.batch_alter_table('sub_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.Enum('online', 'offline', 'hybrid', name='event_type_enum'), nullable=False))
        batch_op.add_column(sa.Column('is_submission_based', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_event', schema=None) as batch_op:
        batch_op.drop_column('is_submission_based')
        batch_op.drop_column('event_type')

    op.drop_table('user_sub_event_positions')
    # ### end Alembic commands ###
