"""empty message

Revision ID: 81c5c36b91ae
Revises: 0b266b7b2f99
Create Date: 2024-10-17 21:43:06.619635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c5c36b91ae'
down_revision = '0b266b7b2f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('result_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
